# Generated by Django 2.2.2 on 2019-07-18 21:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('allowed_devices', models.CharField(blank=True, max_length=250, null=True)),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('allowed_days', models.PositiveIntegerField()),
                ('meeting_place', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], default='', max_length=5)),
                ('designation', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_creation_time', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitors')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_submitted', models.BooleanField(default=False)),
                ('schedule_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.Schedule')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='visitor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.Visitor'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], default='', max_length=3)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, help_text='Your Photo name should be same as your name', null=True, upload_to='profile_photo')),
                ('category', models.CharField(choices=[('GEN', 'General'), ('OBC', 'Other Backward Class'), ('SC', 'Scheduled Caste'), ('ST', 'Scheduled Tribe')], default='', max_length=5)),
                ('blood_group', models.CharField(blank=True, choices=[('OM', 'O-Minus'), ('OP', 'O-Positive'), ('AM', 'A-Minus'), ('AP', 'A-Positive'), ('BM', 'B-Minus'), ('ABM', 'AB-Minus'), ('ABP', 'AB-Positive'), ('BP', 'B-Positive')], max_length=5, null=True)),
                ('designation', models.CharField(choices=[('SC', 'SC'), ('SD', 'SD'), ('SE', 'SE'), ('SF', 'SF'), ('SG', 'SG'), ('SH', 'SH'), ('SEH', 'Section Head'), ('DH', 'Division Head'), ('GH', 'Group Head'), ('GD', 'Group Director'), ('DD', 'Deputy Director'), ('AD', 'Associate Director'), ('D', 'Director'), ('S', 'Student Intern')], default='', max_length=3)),
                ('verified', models.BooleanField(default=False)),
                ('department', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (),
            },
        ),
        migrations.CreateModel(
            name='AllowedDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=250)),
                ('detail', models.TextField()),
                ('visit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visitor.Visit')),
            ],
        ),
    ]
